version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8081:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
  db:
    image: postgres:17beta2-bullseye
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=lighthouse
volumes:
  jenkins_home:
    driver: local
  db-data:
    driver: local
