version: "3.7"
name: automation_center
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - ./docker/volumes/jenkins_home:/var/jenkins_home
  #  db:
  #    image: postgres:17beta2-bullseye
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - ./docker/volumes/PostgresSQL:/var/lib/postgresql/data
  #    environment:
  #      - POSTGRES_USERNAME=postgres
  #      - POSTGRES_PASSWORD=12345
  #      - POSTGRES_DB=lighthouse
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/volumes/grafana:/var/lib/grafana