INSERT INTO TEST_METHOD(ID, NAME, DESCRIPTION) VALUES (0, "TEST NAME 0", "TEST DESCRIPTION 0");
INSERT INTO TEST_METHOD(ID, NAME, DESCRIPTION) VALUES (1, "TEST NAME 1", "TEST DESCRIPTION 1");
INSERT INTO TEST_METHOD(ID, NAME, DESCRIPTION) VALUES (2, "TEST NAME 2", "TEST DESCRIPTION 2");
INSERT INTO TEST_METHOD(ID, NAME, DESCRIPTION) VALUES (3, "TEST NAME 3", "TEST DESCRIPTION 3");
